name: Bug Report
description: File a bug report
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes: 
      value: Create a bug report here
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the bug
      placeholder: Add your description here
    validations:
      required: true
